[[footer]]
name = "Github"
url = "https://github.com/themefisher/"
weight = 2

[[footer]]
name = "Contact"
url = "https://themefisher.com/contact"
weight = 1


# social
[[social]]
name = "ti-facebook"
url = "https://facebook.com/themefisher"

[[social]]
name = "ti-twitter-alt"
url = "https://twitter.com/themefisher"

[[social]]
name = "ti-github"
url = "https://github.com/themefisher"
